export class CommonConstant {
  static readonly FULL_PERCENT: string = '100%'
  static readonly PERCENT_70: string = '70%'
  static readonly PERCENT_20: string = '20%'
  static readonly PERCENT_25: string = '25%'
  static readonly PAGEINFO_KEY: string = 'PageInfo'
  static readonly EXIT_INFO: string = '再按一次退出应用'
  static readonly PREFERENCE_NAME: string = "SP_DEMOS_PREFERENCES"
  static readonly PRIVACY_KEY: string = "PRIVACY_KEY"
  static readonly PRIVACY_AGREED: string = "privacy_agreed"
  static readonly PRE_TIME: number = 0
  static readonly EXIT_TIME: number = 2000
  static readonly OPACITY_01: number = 0.1
  static readonly VP_05: number = 0.5
  static readonly WEIGHT_1: number = 1
  static readonly TAB_INDEX: number = 0
  static readonly TAB_BAR_HEIGHT: number = 0
}